apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-runner-claim
spec:
  storageClassName: alicloud-nas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
